# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ServiceNow Experience Enablement
author: AJ Siegel
email: experiencehub@servicenow.com
description: >- # this means to ignore newlines until "baseurl:"
  Learn how to deliver great experiences with ServiceNow products and the platform through user experience (ux) methods and plays. Learn how to deliver valuable outcomes to your business by using human-centered design (HCD) techniques during your implmentation process.
domain: servicenow.github.io
baseurl: "/Experiencehub" # the subpath of your site, e.g. /blog
url: "https://servicenow.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: servicenow
github_username:  stegel
github:
  owner_name : AJ Siegel
  
###############################################
# --- List of collections --- #
###############################################
collections:
  methods:
    output: true
  outcomes:
    output: true
  plays:
    output: true
  best-practices:
    output: true
  guides: 
    output: true


###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  Outcomes: "/outcomes"
  Methods: "/methods"
  Plays: "/plays"
  Guides: "/guides"
  Best Practices: "/best-practices"
  # Insights: "insights"
  # ServiceNow: "https://www.servicenow.com"



################
# --- Logo --- #
################

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "/assets/images/eo-avatar.jpeg"

# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: false

###########################
# --- General options --- #
###########################

# Add a search button to the navbar
post_search: true


######################################
# --- Colours / background image --- #
######################################

# For any extra visual customization, you can include additional CSS files in every page on your site. List any custom CSS files here
site-css:
  - "/assets/css/custom-styles.css"

##########################
# --- Build Settings --- #
##########################

#remote_theme: pages-themes/cayman@v0.2.0
#remote_theme: daattali/beautiful-jekyll@5.0.0
# theme: daattali/beautiful-jekyll@5.0.0
theme: minima
plugins:
  - jekyll-feed
  - jefyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
